# Generated by Django 5.2.5 on 2025-08-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fix_password_reset_otp_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='person_image',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/person_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
