# Generated by Django 5.2.5 on 2025-08-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_supplier_person_image_supplier_product1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='sub_category',
            new_name='sub_category1',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image1',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image2',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image3',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_image4',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/product_images/'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sub_category2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sub_category3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sub_category4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sub_category5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sub_category6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
